// Renders the brand SVGs in assets/brand/ to the PNG sizes each surface needs.
//
// The SVGs are the source of truth; every PNG here is one of them at a fixed
// size. PNG exists only where a platform refuses an SVG: the PWA manifests
// (Android needs raster icons, and a maskable one) and apple-touch-icon.
//
// Run from the repo root:
//   pnpm build:icons
//
// Chromium comes from the e2e harness, which already installs Playwright —
// this is a once-in-a-while chore, not a build step, so it stays a dependency
// of the harness rather than of the root.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const brand = join(root, "assets", "brand");

const require = createRequire(join(root, "tooling", "harness", "package.json"));
const { chromium } = require("@playwright/test");

/** Every PNG the repo ships, as `source SVG -> where it lands, at what size`. */
const TARGETS = [
  // The app (Vite, served under /app/) and the marketing site both install as
  // PWAs, so both manifests need the same raster set.
  ...["apps/app/public", "apps/www/public"].flatMap((out) => [
    { svg: "icon.svg", out: `${out}/icon-192x192.png`, size: 192 },
    { svg: "icon.svg", out: `${out}/icon-512x512.png`, size: 512 },
    { svg: "icon.svg", out: `${out}/apple-touch-icon.png`, size: 180 },
    {
      svg: "icon-maskable.svg",
      out: `${out}/icon-maskable-512x512.png`,
      size: 512,
    },
  ]),
  // Next's file convention: app/apple-icon.png is emitted as the touch icon.
  { svg: "icon.svg", out: "apps/www/app/apple-icon.png", size: 180 },
];

/**
 * SVG favicons, copied rather than re-drawn: each app serves its own static
 * directory, and a copy keeps assets/brand/ the only place the mark is edited.
 */
const COPIES = [
  { svg: "icon.svg", out: "apps/app/public/icon.svg" },
  { svg: "icon.svg", out: "apps/www/app/icon.svg" },
  { svg: "icon-admin.svg", out: "apps/admin/public/icon.svg" },
];

for (const { svg, out } of COPIES) {
  const target = join(root, out);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(
    target,
    `<!-- Generated by scripts/build-icons.mjs from assets/brand/${svg}. Edit that file. -->\n${await readFile(join(brand, svg), "utf8")}`,
  );
  console.log(`${svg} -> ${out}`);
}

const browser = await chromium.launch();
const page = await browser.newPage();

for (const { svg, out, size } of TARGETS) {
  const markup = await readFile(join(brand, svg), "utf8");
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<!doctype html><style>html,body{margin:0;padding:0}svg{display:block}</style>${markup.replace("<svg", `<svg width="${size}" height="${size}"`)}`,
  );
  const shot = await page.screenshot({ omitBackground: true });
  const target = join(root, out);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, shot);
  console.log(`${svg} -> ${out} (${size}px)`);
}

await browser.close();
